apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garmin-data-pvc
  namespace: default
  labels:
    app: garmin-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # minikube provides the "standard" storage class by default
  storageClassName: standard
